CREATE TABLE IF NOT EXISTS public.players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  birth_date DATE NOT NULL,
  age INTEGER NOT NULL CHECK (age BETWEEN 40 AND 90),
  contact_number TEXT NOT NULL,
  email TEXT,
  team_name TEXT NOT NULL,
  jersey_number TEXT NOT NULL,
  player_position TEXT NOT NULL,
  height TEXT,
  weight TEXT,
  emergency_contact TEXT NOT NULL,
  address TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS players_registered_at_idx
ON public.players (registered_at DESC);

ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;

-- The app writes and exports through Vercel API routes using the Supabase
-- service-role key, which bypasses RLS. No public table policies are needed.
